datasource:
  url: jdbc:mysql://rm-2ze6tlyn0l3812nsmqo.mysql.rds.aliyuncs.com:3306/mecdata
  userName: alan
  password: Sun196130
#  url: jdbc:mysql://10.28.237.217:3306/mecdata?serverTimezone=GMT
#  userName: root
#  password: sun196130
  databaseName: mecdata

connectPool:
  coreSize: 30
  maxSize: 100


